name: Cleanup (cron)
on:
  schedule:
  - cron: '0 * * * *' # every hour
#    - cron: '30 10 * * SUN' # every sunday at 10:30

jobs:
  deleteArtifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.CLEANUP_GITHUB_TOKEN }}
          expire-in: 2 days
#          expire-in: 21 days