name: Reusable workflow example

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
      color:
        required: false
        type: string
      messageFailed:
        required: false
        type: string
      hasFailed:
        required: false
        type: boolean
    secrets:
      token:
        required: true
      webhook:
        required: true

jobs:
  sendMessage: 
    name: Discord Message
    runs-on: ubuntu-latest
    steps:
        - uses: appleboy/discord-action@master
        - name: send custom message with args
          if:  ${{ !inputs.hasFailed }}
          with:
            webhook_id: ${{ secrets.webhook }}
            webhook_token: ${{ secrets.token }}
            color: "#00FF00"
            args: | 
                ${{ inputs.message }}
                The workflow runs at
                https://github.com/${{ github.repository }}/actions/runs/${{github.run_id}}.
        - name: send error message with args
        - uses: appleboy/discord-action@master
          if:  ${{ inputs.hasFailed }}
          with:
            webhook_id: ${{ secrets.webhook }}
            webhook_token: ${{ secrets.token }}
            color: "#FF0000"
            args: | 
                ${{ inputs.messageFailed }}
                The workflow runs at
                https://github.com/${{ github.repository }}/actions/runs/${{github.run_id}}.       
