name: Reusable workflow example

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
    secrets:
      token:
        required: true
      webhook:
        required: true

jobs:
  sendMessage: 
    name: Discord Message
    runs-on: ubuntu-latest
    steps:
        - name: send custom message with args
          uses: appleboy/discord-action@master
          with:
            webhook_id: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
            webhook_token: ${{ secrets.DISCORD_WEBHOOK_ID }}
            args: | 
                ${{ inputs.message }}
                The workflow runs at
                https://github.com/${{ github.repository }}/actions/runs/${{github.run_id}}.