name: Release new version ⭐

on:
  push:
    tags: 
      - v*

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  sendInitialMessage: 
    name: Discord Initial Message
    runs-on: ubuntu-latest
    steps:
        - name: send custom message with args
          uses: appleboy/discord-action@master
          with:
            webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
            webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
            color: "#00FF00"
            args: | 
                Build workflow has been queued 
                Target platfrom WebGL
                The workflow runs at
                https://github.com/${{ github.repository }}/actions/runs/${{github.run_id}}.

  checkLicense:
    name: Check for the Unity license ☑️
    runs-on: ubuntu-latest
    steps:
      - name: Fail - No license ☠️
        if: ${{ !startsWith(env.UNITY_LICENSE, '<') }}
        run: exit 1

  testRunner:
    needs: checkLicense
    name: Test all modes 📝
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Restore Library cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-test-project
          restore-keys: |
            Library-test-project-
            Library-

      - uses: webbertakken/unity-test-runner@v2
        id: testRunner
        with:
          testMode: all

      - uses: actions/upload-artifact@v2
        with:
          name: Test results (all modes)
          path: ${{ steps.testRunner.outputs.artifactsPath }}

  testMessage: 
   name: Test Message
   needs: testRunner
   uses: KostasBan/Actions-for-Unity-CI/.github/workflows/discordMessage.yml@development
   if: always()
   with:
      message: |
            Build workflow passed all tests
            Target platfrom WebGL
      jobResult:  ${{ needs.testRunner.result }}
      messageFailed: |
             Build workflow Failed one or more tests
             The Process is terminated
             Target platfrom WebGL
   secrets:
      token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
      webhook: ${{ secrets.DISCORD_WEBHOOK_ID  }}

  buildWebGL:
    needs: testRunner
    name: Build for WebGL 🖥️
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Restore Library cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-build-WebGL
          restore-keys: |
            Library-build-
            Library-

      - uses: game-ci/unity-builder@v2
        with:
            targetPlatform: WebGL
            versioning: Tag
            allowDirtyBuild: true

      - uses: actions/upload-artifact@v2
        with:
          name: build-WebGL
          path: build/WebGL
  
  buildMessage: 
   name: Build Message
   needs: buildWebGL
   uses: KostasBan/Actions-for-Unity-CI/.github/workflows/discordMessage.yml@development
   if: always()
   with:
      message: |
            Build workflow Completed
            Target platfrom WebGL
      jobResult:  ${{ needs.buildWebGL.result }}
      messageFailed: |
             Build workflow Failed while building
             The Process is terminated
             Target platfrom WebGL
   secrets:
      token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
      webhook: ${{ secrets.DISCORD_WEBHOOK_ID  }}
 
  deployPages:
    needs: buildWebGL
    name: Deploy to Github Pages 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: build-WebGL
          path: build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build/WebGL

  deployMessage: 
   name: Deploy Message
   needs: deployPages
   uses: KostasBan/Actions-for-Unity-CI/.github/workflows/discordMessage.yml@development
   if: always()
   with:
      message: |
             Build successfully deployed at
             https://kostasban.github.io/Actions-for-Unity-CI/
      jobResult:  ${{ needs.deployPages.result  }}
      messageFailed: |
                Build workflow Failed while trying to deploy the build
                The Process is terminated
                Target platfrom WebGL
   secrets:
      token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
      webhook: ${{ secrets.DISCORD_WEBHOOK_ID  }}