name: TestWorkflow

on: [push, pull_request]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  sendMessage: 
   name: Initial Message
   uses: KostasBan/Actions-for-Unity-CI/.github/workflows/discordMessage.yml@kostasban/sc-49/more-reusable-workflows
   secrets:
      token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
      webhook: ${{ secrets.DISCORD_WEBHOOK_ID  }}

  buildWindows:
    name: Build
    uses: KostasBan/Actions-for-Unity-CI/.github/workflows/windowsBuild.yml@kostasban/sc-49/more-reusable-workflows
#  testRunner:
#    name: Test all modes 📝
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Create LFS file list
#        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
#
#      - name: Restore LFS cache
#        uses: actions/cache@v2
#        id: lfs-cache
#        with:
#          path: .git/lfs
#          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
#
#      - name: Git LFS Pull
#        run: |
#          git lfs pull
#          git add .
#          git reset --hard
#
#      - name: Restore Library cache
#        uses: actions/cache@v2
#        with:
#          path: Library
#          key: Library-test-project
#          restore-keys: |
#            Library-test-project-
#            Library-
#
#      - uses: webbertakken/unity-test-runner@v2
#        id: testRunner
#        with:
#          testMode: all
#
#      - uses: actions/upload-artifact@v2
#        with:
#          name: Test results (all modes)
#          path: ${{ steps.testRunner.outputs.artifactsPath }}
#
#  testMessage: 
#   name: Test Message
#   needs: testRunner
#   uses: KostasBan/Actions-for-Unity-CI/.github/workflows/discordMessage.yml@kostasban/sc-47/reusable-workflows
#   if: always()
#   with:
#      message: |
#            Build workflow passed all tests
#            Target platfrom WebGL
#      hasFailed:  ${{ needs.testRunner.result == 'failure' }}
#      messageFailed: |
#             Build workflow Failed one or more tests
#             The Process is terminated
#             Target platfrom WebGL
#   secrets:
#      token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
#      webhook: ${{ secrets.DISCORD_WEBHOOK_ID  }}
#