name: Reusable workflow for making a windows build

on:
  workflow_call:
    inputs:
      runnerOS:
        required: true
        type: string
      hashFiles:
        required: true
        type: string
#      messageFailed:
#        required: false
#        type: string
#      hasFailed:
#        required: false
#        type: boolean
#    secrets:
#      token:
#        required: true
#      webhook:
#        required: true

jobs:
  buildWindows:
    name: Build for Windows 🖥️
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: test
        run: echo ${{ inputs.hashFiles }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ inputs.runnerOS }}-lfs-${{ inputs.hashFiles }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Restore Library cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-build-StandaloneWindows64
          restore-keys: |
            Library-build-
            Library-

      - uses: webbertakken/unity-builder@v2
        with:
          targetPlatform: StandaloneWindows64

      - uses: actions/upload-artifact@v2
        with:
          name: build-StandaloneWindows64
          path: build/StandaloneWindows64
